
TWITER: 1
RoMy: Si tu supieras que yo .... (8)

TWITER: 2

ERROR AL LEER LINEA  2

TWITER: 2
kmii andrea saez : http://t.co/sCRRrG8  claro esta cancion la coloca el y me representa a mi  .l.

TWITER: 3

ERROR AL LEER LINEA  4

TWITER: 3

ERROR AL LEER LINEA  5

TWITER: 3
rodrigo jara: @tito_kuriko dame un seg

TWITER: 4
Carlos Sepulveda: @Val3ee yo soy un hombre lobo! 1313 xDD jajaja

TWITER: 5
Claudia Artiaga: @cocaventuras :) Me too

TWITER: 6

ERROR AL LEER LINEA  9

TWITER: 6
Tamara Botta: @RodrigoPulgar Jajajaja

TWITER: 7

ERROR AL LEER LINEA  11

TWITER: 7

ERROR AL LEER LINEA  12

TWITER: 7

ERROR AL LEER LINEA  13

TWITER: 7

ERROR AL LEER LINEA  14

TWITER: 7
betho puntoaparte: @Mark_LaiS agregado :D

TWITER: 8

ERROR AL LEER LINEA  16

TWITER: 8

ERROR AL LEER LINEA  17

TWITER: 8

ERROR AL LEER LINEA  18

TWITER: 8
Franco castillo : Que pelicula me gusta ! RT @ValecitaDYCHILE: Busqueda Implacable  . . .La veo en el Fox :]

TWITER: 9
Karla Arenas Pardo: @Iamproudofnando JAJAJAJAJAJA EN LA MIA TAMPOCO :(

TWITER: 10
kmii andrea saez : @DarvuWaffle  que sean 2 :C

TWITER: 11
Ulises Zaracho: @caaaaarolinna Jajaja vi a una chica que dijo que mas que seguro que son ropas de ellos dos

TWITER: 12

ERROR AL LEER LINEA  23

TWITER: 12

ERROR AL LEER LINEA  24

ERROR AL LEER LINEA  25
